@baseUrl = http://localhost:3000/exchangeOffers

GET {{baseUrl}}/7

###
GET {{baseUrl}}

###
POST {{baseUrl}}
Content-Type:  application/json

{
  "OfferedBookID": 1,
  "RequestedBookID": 2,
  "OfferingUserID": 1,
  "RequestingUserID": 2,
  "OfferDate": "2023-03-15",
  "StatusID": 1
}



###
PUT  {{baseUrl}}
Content-Type:  application/json

{
  "OfferID": 7,
  "StatusID": 2
}

